# Version
version: "3.1"

# Setup services
services:
  # Node 1
  docker-ubuntu-sftp-1:
    container_name: docker-ubuntu-sftp-1
    image: docker-ubuntu-sftp
    restart: no
    ports:
      - 2220:22
    networks:
      - ubuntu-sftp-net
    volumes:
      - ./sftp-docker-1:/home/sftp

  # Node 2
  docker-ubuntu-sftp-2:
    container_name: docker-ubuntu-sftp-2
    image: docker-ubuntu-sftp
    restart: no
    ports:
      - 2221:22
    networks:
      - ubuntu-sftp-net
    volumes:
      - ./sftp-docker-2:/home/sftp

# Networks
networks:
  ubuntu-sftp-net:
    name: ubuntu-sftp-net
